GET http://localhost:5000/food
content-type: application/json

###

POST http://localhost:5000/food
content-type: application/json

{
    "name": "Almoço",
    "url": "https://i0.wp.com/pat.feldman.com.br/wp-content/uploads/2012/01/comida-caseira.jpg?fit=960%2C540&ssl=1",
    "price": 20
}

###

PUT  http://localhost:5000/food/8bbdb541-05ff-4a70-84bc-b9fb925597cd
content-type: application/json

{
    "name": "Almoço Editado",
    "url": "https://i0.wp.com/pat.feldman.com.br/wp-content/uploads/2012/01/comida-caseira.jpg?fit=960%2C540&ssl=1",
    "price": 25
}